routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', ['uses'=>'Controller@homepage']);
Route::post('/logout', ['as'=>'logout', 'uses'=>'Controller@logout']);
Route::get('/cadastrar', ['uses'=>'Controller@cadastrar']);
Route::get('/logout', ['uses'=>'Controller@logout']);
Route::get('/dashboard', ['as'=>'user.dashboard', 'uses'=>'DashboardController@index']);
Route::get('/logar', ['as'=>'user.login', 'uses'=>'Controller@homepage']);
Route::get('/cadastro', ['as'=>'user.cadastro', 'uses'=>'UsersController@index']);
Route::post('/loadSchedule', ['as'=>'schedule.loadSchedule', 'uses'=>'SchedulesController@loadSchedule']);
Route::post('/logar', ['as'=>'dashboard.auth', 'uses'=>'DashboardController@auth']);    
Route::get('/cadastrar', ['as'=>'room.cadastrar', 'uses'=>'RoomsController@cadastrarSala']);
Route::post('/delete', ['as'=>'schedule.delete', 'uses'=>'SchedulesController@delete']);
Route::resource('schedule', 'SchedulesController');
Route::resource('user', 'UsersController');
Route::resource('room', 'RoomsController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/templates/master.blade.php
<!DOCTYPE html>
<html lang="pt-br">
    <header>
        <meta charset="UTF-8">
        <title>Meeting rooms</title>
        
        <link rel="stylesheet" href="{{ asset('css/stylesheet.css') }}"
        <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
        @yield('css-view')
    </header>
    <body>
        @include('templates.menu-lateral')
        <section id="view-content">
        @yield('content-view')
    </section>
        @yield('js-view')
    </body>
</html>

resources/views/templates/menu-lateral.blade.php
<nav id="principal">
    <ul>
             
        <li>
                <a href="cadastrar">
                    <i class=""></i>
                    <h3>Cadastrar Salas</h3>
                </a>
            </li>                
            <li>
                       <a href="{{ route('room.index')}}">
                        <i class=""></i>
                        <h3>Reservar Salas</h3>
                    </a>
                </li>
                <li>
                    <a href="{{ route('user.cadastro')}}">
                     <i class=""></i>
                     <h3>Cadastrar Usuários</h3>
                 </a>
             </li>
                       <li>
            <a href="">
                <i class=""></i>
                {!! Form::open(['route'=>'logout', 'method' => 'get', 'class' => 'form-padrao']) !!}
                @include ('templates.formulario.submit', ['input' => 'Logout'])
                {!! Form::close() !!}
            </a>
        </li>
    </ul>

</nav>